[package]
name = "git-hooks"
version = "0.1.0"
authors = ["Simon Wörner <git@simon-woerner.de>"]
edition = "2021"

[dev-dependencies]
cargo-husky = { version = "1.5.0", default-features = false, features = [
    "precommit-hook",
    "prepush-hook",
    "run-cargo-check",
    "run-cargo-fmt",
] }
